/**
 * Question Generation Types
 *
 * Comprehensive type definitions for AI-powered question generation,
 * educational validation, and assessment delivery.
 *
 * Designed by a Principal Educational Technology Engineer with expertise in:
 * - Adaptive assessment design
 * - Psychometric analysis
 * - AI-powered question generation
 * - Universal Design for Learning (UDL)
 *
 * @module questions.types
 */

import type { BaselineDomain, GradeBand } from './baseline.js';

// ═══════════════════════════════════════════════════════════════════════════════
// CORE ENUMS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Supported question types following best practices in educational assessment.
 * Each type maps to specific cognitive demands and response patterns.
 */
export type QuestionType =
  | 'multiple-choice' // 4-option MC, single correct answer
  | 'multiple-select' // Multi-correct MC (check all that apply)
  | 'short-answer' // Brief text response (1-3 sentences)
  | 'matching' // Pair items from two lists
  | 'ordering' // Arrange items in correct sequence
  | 'fill-blank' // Complete sentence with missing word(s)
  | 'true-false' // Binary choice
  | 'constructed-response'; // Extended written response

/**
 * Bloom's Taxonomy cognitive levels for question classification.
 * Higher levels indicate deeper cognitive processing required.
 */
export type CognitiveLevel =
  | 'remember' // Recall facts, terms, basic concepts (Level 1)
  | 'understand' // Explain ideas, interpret meaning (Level 2)
  | 'apply' // Use information in new situations (Level 3)
  | 'analyze' // Draw connections, identify patterns (Level 4)
  | 'evaluate' // Justify, critique, make judgments (Level 5)
  | 'create'; // Produce original work, design solutions (Level 6)

/**
 * Difficulty tiers aligned with grade-level expectations.
 */
export type DifficultyLevel = 'foundational' | 'grade-level' | 'challenging';

/**
 * Risk levels for content validation.
 */
export type ContentRiskLevel = 'safe' | 'review' | 'flagged' | 'blocked';

/**
 * Question source for provenance tracking.
 */
export type QuestionSource =
  | 'ai-generated' // Generated by AI during assessment
  | 'curated-bank' // From reviewed question bank
  | 'static-fallback' // Last-resort static questions
  | 'teacher-created' // Teacher-authored questions
  | 'imported'; // Imported from external source

// ═══════════════════════════════════════════════════════════════════════════════
// LEARNER ACCOMMODATIONS (IDEA/Section 504 Aligned)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Learner accommodations aligned with IDEA and Section 504 requirements.
 * These modify question presentation without changing construct measured.
 */
export interface LearnerAccommodations {
  // ── Presentation Accommodations ──
  /** Text-to-speech for question stem and options */
  readAloud?: boolean;
  /** Larger text size (1.25x - 2x normal) */
  largeText?: boolean;
  /** High contrast color scheme */
  highContrast?: boolean;
  /** Visual supports and diagrams for concepts */
  visualSupports?: boolean;
  /** Simplified vocabulary (Flesch-Kincaid grade level reduction) */
  simplifiedLanguage?: boolean;
  /** Bilingual presentation with native language support */
  bilingualSupport?: {
    enabled: boolean;
    primaryLanguage: string; // ISO 639-1 code
  };

  // ── Response Accommodations ──
  /** Extended time multiplier (1.5x, 2x, unlimited) */
  extendedTime?: number | 'unlimited';
  /** Allow speech-to-text for responses */
  speechToText?: boolean;
  /** Allow dictation/scribe input */
  dictation?: boolean;
  /** Allow calculator for math questions */
  calculator?: boolean;

  // ── Setting Accommodations ──
  /** Reduced distractions (simplified UI, fewer elements) */
  reducedDistractions?: boolean;
  /** Frequent breaks between questions */
  frequentBreaks?: boolean;
  /** Break interval in minutes */
  breakIntervalMinutes?: number;

  // ── Format Modifications ──
  /** Reduce number of options (3 instead of 4) */
  reducedOptions?: boolean;
  /** Simplify matching/ordering (fewer items) */
  reducedItems?: boolean;
  /** Chunk content into smaller segments */
  chunkedContent?: boolean;

  // ── Assistive Technology ──
  /** Screen reader compatible formatting */
  screenReaderOptimized?: boolean;
  /** Switch scanning support */
  switchScanning?: boolean;
  /** Eye tracking interface */
  eyeTracking?: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════════
// QUESTION GENERATION REQUEST
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Previous response data for adaptive question generation.
 * Enables AI to adjust difficulty and focus based on learner performance.
 */
export interface PreviousResponse {
  skillCode: string;
  questionType: QuestionType;
  wasCorrect: boolean;
  latencyMs: number;
  difficulty: number;
  cognitiveLevel: CognitiveLevel;
}

/**
 * Standards alignment information for curriculum mapping.
 */
export interface StandardsContext {
  /** Common Core State Standards codes */
  ccssStandards?: string[];
  /** Next Generation Science Standards */
  ngssStandards?: string[];
  /** State-specific standards codes */
  stateStandards?: {
    state: string;
    codes: string[];
  };
}

/**
 * Request payload for AI question generation.
 * Provides full context for generating educationally valid questions.
 */
export interface QuestionGenerationRequest {
  // ── Identification ──
  tenantId: string;
  learnerId: string;
  assessmentSessionId?: string;

  // ── Academic Context ──
  subject: BaselineDomain;
  gradeLevel: number; // Numeric grade (K=0, 1-12)
  gradeBand: GradeBand;
  topicArea: string; // Specific topic within domain
  skillCodes: string[]; // Skill codes to assess

  // ── Question Parameters ──
  difficultyLevel: DifficultyLevel;
  targetDifficulty?: number; // 0-1 scale for adaptive
  questionCount: number;
  questionTypes: QuestionType[];

  // ── Adaptive Context ──
  previousResponses?: PreviousResponse[];
  currentAbilityEstimate?: number; // IRT theta estimate

  // ── Accommodations ──
  accommodations?: LearnerAccommodations;

  // ── Standards ──
  standardsContext?: StandardsContext;

  // ── Generation Preferences ──
  preferences?: {
    /** Avoid questions similar to recent ones */
    avoidSimilar?: boolean;
    /** Prefer practical/real-world contexts */
    realWorldContexts?: boolean;
    /** Include visual elements when applicable */
    includeVisuals?: boolean;
    /** Cultural context preferences */
    culturalContext?: string;
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// GENERATED QUESTION
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Question option for multiple-choice type questions.
 */
export interface QuestionOption {
  id: string; // Stable identifier (A, B, C, D)
  text: string;
  isCorrect: boolean;
  /** Explanation of why this is correct/incorrect */
  rationale?: string;
  /** Distractor analysis for incorrect options */
  distractorType?:
    | 'common-misconception'
    | 'partial-understanding'
    | 'careless-error'
    | 'plausible-alternative';
}

/**
 * Matching pair for matching-type questions.
 */
export interface MatchingPair {
  leftItem: string;
  rightItem: string;
  leftId: string;
  rightId: string;
}

/**
 * Rich metadata for question analytics and improvement.
 */
export interface QuestionMetadata {
  // ── Generation Info ──
  source: QuestionSource;
  generatedAt: string; // ISO timestamp
  generationModel?: string; // AI model version
  generationLatencyMs?: number;

  // ── Educational Properties ──
  /** Flesch-Kincaid Grade Level */
  readingLevel: number;
  /** Word count of question stem */
  wordCount: number;
  /** Estimated completion time in seconds */
  estimatedTimeSeconds: number;

  // ── Psychometric Properties ──
  /** IRT difficulty parameter (b) */
  irtDifficulty?: number;
  /** IRT discrimination parameter (a) */
  irtDiscrimination?: number;
  /** Guessing parameter (c) for MC */
  irtGuessing?: number;

  // ── Quality Scores ──
  /** Overall quality score (0-1) */
  qualityScore?: number;
  /** Clarity of stem (0-1) */
  clarityScore?: number;
  /** Distractor quality for MC (0-1) */
  distractorQuality?: number;

  // ── Content Safety ──
  contentRiskLevel: ContentRiskLevel;
  contentFlags?: string[];

  // ── Usage Tracking ──
  timesUsed?: number;
  lastUsed?: string;
  averageResponseTime?: number;
  correctRate?: number;
}

/**
 * Visual element for questions requiring images/diagrams.
 */
export interface QuestionVisual {
  type: 'image' | 'diagram' | 'chart' | 'graph' | 'equation';
  url?: string;
  altText: string;
  /** LaTeX or SVG for rendered content */
  content?: string;
  position: 'before-stem' | 'after-stem' | 'with-options';
}

/**
 * AI-generated assessment question with full educational metadata.
 */
export interface GeneratedQuestion {
  // ── Identification ──
  id: string;
  skillCode: string;

  // ── Question Content ──
  type: QuestionType;
  /** Main question text */
  stem: string;
  /** Additional context or passage */
  passage?: string;
  /** Instructions specific to question type */
  instructions?: string;
  /** Visual elements */
  visuals?: QuestionVisual[];

  // ── Answer Structure ──
  /** Options for MC/matching questions */
  options?: QuestionOption[];
  /** Pairs for matching questions */
  matchingPairs?: MatchingPair[];
  /** Items for ordering questions */
  orderingItems?: string[];
  /** Correct answer(s) */
  correctAnswer: string | string[] | number;
  /** Acceptable alternatives for short-answer */
  acceptableAnswers?: string[];

  // ── Educational Context ──
  /** Explanation of correct answer */
  explanation: string;
  /** Common misconceptions addressed */
  misconceptions?: string[];
  /** Hints for scaffolded support */
  hints?: string[];
  /** Standards aligned to this question */
  standardsAlignment: string[];

  // ── Properties ──
  /** Difficulty on 0-1 scale */
  difficulty: number;
  /** Bloom's taxonomy level */
  cognitiveLevel: CognitiveLevel;

  // ── Metadata ──
  metadata: QuestionMetadata;
}

// ═══════════════════════════════════════════════════════════════════════════════
// QUESTION GENERATION RESPONSE
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Response from question generation including quality metrics.
 */
export interface QuestionGenerationResponse {
  /** Generated questions */
  questions: GeneratedQuestion[];

  /** Generation metadata */
  generationId: string;
  generatedAt: string;

  /** Quality summary */
  qualitySummary: {
    averageQuality: number;
    averageDifficulty: number;
    cognitiveDistribution: Record<CognitiveLevel, number>;
    typeDistribution: Record<QuestionType, number>;
    questionsPassedValidation: number;
    questionsFailedValidation: number;
  };

  /** Source information */
  sourceBreakdown: {
    aiGenerated: number;
    curatedBank: number;
    staticFallback: number;
  };

  /** Accommodations applied */
  accommodationsApplied: (keyof LearnerAccommodations)[];

  /** Warnings or notes */
  warnings?: string[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// VALIDATION TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Individual validation rule result.
 */
export interface ValidationRuleResult {
  rule: string;
  passed: boolean;
  severity: 'error' | 'warning' | 'info';
  message: string;
  details?: Record<string, unknown>;
}

/**
 * Complete validation result for a question.
 */
export interface QuestionValidationResult {
  questionId: string;
  isValid: boolean;
  overallScore: number; // 0-1
  rules: ValidationRuleResult[];
  suggestions?: string[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// QUESTION BANK TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Query parameters for question bank retrieval.
 */
export interface QuestionBankQuery {
  domain: BaselineDomain;
  gradeBand: GradeBand;
  skillCodes?: string[];
  difficultyRange?: { min: number; max: number };
  questionTypes?: QuestionType[];
  cognitiveLevel?: CognitiveLevel;
  count: number;
  /** Exclude questions by ID (recently used) */
  excludeIds?: string[];
  /** Standards to match */
  standards?: string[];
}

/**
 * Curated question from the question bank.
 */
export interface CuratedQuestion extends GeneratedQuestion {
  /** Review status */
  reviewStatus: 'pending' | 'approved' | 'rejected' | 'needs-revision';
  /** Reviewer information */
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;
  /** Version for update tracking */
  version: number;
  /** Created/updated timestamps */
  createdAt: string;
  updatedAt: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ANALYTICS TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Question-level analytics for performance tracking.
 */
export interface QuestionAnalytics {
  questionId: string;
  skillCode: string;

  // ── Usage Metrics ──
  totalAttempts: number;
  uniqueLearners: number;

  // ── Performance Metrics ──
  correctRate: number; // Proportion correct
  averageLatencyMs: number;
  medianLatencyMs: number;

  // ── Psychometric Metrics ──
  /** Point-biserial correlation */
  discriminationIndex: number;
  /** IRT difficulty estimate */
  difficultyEstimate: number;
  /** Item-total correlation */
  itemTotalCorrelation: number;

  // ── Distractor Analysis (MC only) ──
  optionDistribution?: Record<string, number>;
  distractorEffectiveness?: Record<string, number>;

  // ── Quality Indicators ──
  skipRate: number;
  timeoutRate: number;
  feedbackScores?: {
    average: number;
    count: number;
  };

  // ── Time Period ──
  periodStart: string;
  periodEnd: string;
}

/**
 * AI generation analytics for monitoring quality.
 */
export interface AIGenerationAnalytics {
  periodStart: string;
  periodEnd: string;

  // ── Generation Metrics ──
  totalRequests: number;
  successfulGenerations: number;
  failedGenerations: number;
  averageLatencyMs: number;
  p95LatencyMs: number;

  // ── Quality Metrics ──
  averageQualityScore: number;
  validationPassRate: number;
  averageReadingLevel: number;

  // ── Fallback Metrics ──
  curatedBankFallbacks: number;
  staticFallbacks: number;

  // ── Error Breakdown ──
  errorsByType: Record<string, number>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// SERVICE INTERFACES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Question Generator Service Interface
 */
export interface IQuestionGeneratorService {
  /**
   * Generate questions using AI with fallback chain.
   */
  generateQuestions(request: QuestionGenerationRequest): Promise<QuestionGenerationResponse>;

  /**
   * Validate a question against educational standards.
   */
  validateQuestion(question: GeneratedQuestion): Promise<QuestionValidationResult>;

  /**
   * Get questions from curated bank.
   */
  getFromQuestionBank(query: QuestionBankQuery): Promise<GeneratedQuestion[]>;

  /**
   * Invalidate cached questions for regeneration.
   */
  invalidateCache(key: string): Promise<void>;
}

/**
 * Question Analytics Service Interface
 */
export interface IQuestionAnalyticsService {
  /**
   * Record a question response for analytics.
   */
  recordResponse(params: {
    questionId: string;
    learnerId: string;
    isCorrect: boolean;
    latencyMs: number;
    selectedOption?: string;
    source: QuestionSource;
  }): Promise<void>;

  /**
   * Get analytics for a specific question.
   */
  getQuestionAnalytics(questionId: string): Promise<QuestionAnalytics | null>;

  /**
   * Get AI generation analytics for monitoring.
   */
  getGenerationAnalytics(startDate: string, endDate: string): Promise<AIGenerationAnalytics>;

  /**
   * Get questions that need review based on performance.
   */
  getQuestionsNeedingReview(): Promise<{ questionId: string; reason: string }[]>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Default question generation configuration.
 */
export const QUESTION_GENERATION_DEFAULTS = {
  questionCount: 5,
  defaultDifficulty: 'grade-level' as DifficultyLevel,
  maxRetries: 3,
  timeoutMs: 30000,
  minQualityScore: 0.7,
  targetReadingLevelOffset: -1, // One grade below for accessibility
} as const;

/**
 * Cognitive level weights for balanced assessments.
 */
export const COGNITIVE_LEVEL_WEIGHTS: Record<CognitiveLevel, number> = {
  remember: 0.15,
  understand: 0.25,
  apply: 0.3,
  analyze: 0.2,
  evaluate: 0.07,
  create: 0.03,
};

/**
 * Question type configurations.
 */
export const QUESTION_TYPE_CONFIG: Record<
  QuestionType,
  { minOptions: number; maxOptions: number; requiresExplanation: boolean }
> = {
  'multiple-choice': { minOptions: 4, maxOptions: 4, requiresExplanation: true },
  'multiple-select': { minOptions: 4, maxOptions: 6, requiresExplanation: true },
  'short-answer': { minOptions: 0, maxOptions: 0, requiresExplanation: true },
  matching: { minOptions: 3, maxOptions: 6, requiresExplanation: false },
  ordering: { minOptions: 3, maxOptions: 6, requiresExplanation: true },
  'fill-blank': { minOptions: 0, maxOptions: 0, requiresExplanation: true },
  'true-false': { minOptions: 2, maxOptions: 2, requiresExplanation: true },
  'constructed-response': { minOptions: 0, maxOptions: 0, requiresExplanation: true },
};

/**
 * Reading level targets by grade.
 */
export const READING_LEVEL_TARGETS: Record<GradeBand, { min: number; max: number }> = {
  K5: { min: 0, max: 5 },
  G6_8: { min: 5, max: 8 },
  G9_12: { min: 8, max: 12 },
};
