import 'package:json_annotation/json_annotation.dart';
import '../device/device_models.dart';

part 'shared_device_models.g.dart';

/// Mode of device operation
enum DeviceMode {
  /// Personal device - single learner, full auth
  personal,
  /// Shared device - kiosk mode, class code + roster + PIN
  shared,
}

/// Privacy display mode for roster
enum RosterDisplayMode {
  /// Full first name + last initial (e.g., "John S.")
  firstNameLastInitial,
  /// Pseudonym only (e.g., "Blue Tiger 7")
  pseudonym,
  /// First name only (e.g., "John")
  firstNameOnly,
}

/// Session code generated by teacher for shared device login
@JsonSerializable()
class ClassSessionCode {
  final String code;
  final String classroomId;
  final String classroomName;
  final String teacherId;
  final String teacherName;
  final DateTime expiresAt;
  final bool isActive;

  ClassSessionCode({
    required this.code,
    required this.classroomId,
    required this.classroomName,
    required this.teacherId,
    required this.teacherName,
    required this.expiresAt,
    required this.isActive,
  });

  factory ClassSessionCode.fromJson(Map<String, dynamic> json) =>
      _$ClassSessionCodeFromJson(json);

  Map<String, dynamic> toJson() => _$ClassSessionCodeToJson(this);

  bool get isExpired => DateTime.now().isAfter(expiresAt);
  bool get isValid => isActive && !isExpired;
}

/// Learner entry in class roster for shared device selection
@JsonSerializable()
class RosterLearner {
  final String learnerId;
  final String displayName;
  final String? avatarUrl;
  final String? pseudonym;
  final GradeBand? gradeBand;
  final bool hasPin;

  RosterLearner({
    required this.learnerId,
    required this.displayName,
    this.avatarUrl,
    this.pseudonym,
    this.gradeBand,
    this.hasPin = true,
  });

  factory RosterLearner.fromJson(Map<String, dynamic> json) =>
      _$RosterLearnerFromJson(json);

  Map<String, dynamic> toJson() => _$RosterLearnerToJson(this);

  /// Get display name based on privacy mode
  String getDisplayName(RosterDisplayMode mode) {
    switch (mode) {
      case RosterDisplayMode.pseudonym:
        return pseudonym ?? displayName;
      case RosterDisplayMode.firstNameOnly:
        return displayName.split(' ').first;
      case RosterDisplayMode.firstNameLastInitial:
        return displayName;
    }
  }
}

/// Classroom roster response from backend
@JsonSerializable()
class ClassroomRoster {
  final String classroomId;
  final String classroomName;
  final String teacherName;
  final GradeBand? gradeBand;
  final RosterDisplayMode displayMode;
  final List<RosterLearner> learners;
  final DateTime fetchedAt;

  ClassroomRoster({
    required this.classroomId,
    required this.classroomName,
    required this.teacherName,
    this.gradeBand,
    this.displayMode = RosterDisplayMode.firstNameLastInitial,
    required this.learners,
    DateTime? fetchedAt,
  }) : fetchedAt = fetchedAt ?? DateTime.now();

  factory ClassroomRoster.fromJson(Map<String, dynamic> json) =>
      _$ClassroomRosterFromJson(json);

  Map<String, dynamic> toJson() => _$ClassroomRosterToJson(this);
}

/// Active shared device session state
@JsonSerializable()
class SharedDeviceSession {
  final String sessionId;
  final String classroomId;
  final String classroomName;
  final String learnerId;
  final String learnerDisplayName;
  final DateTime startedAt;
  final GradeBand? gradeBand;

  SharedDeviceSession({
    required this.sessionId,
    required this.classroomId,
    required this.classroomName,
    required this.learnerId,
    required this.learnerDisplayName,
    required this.startedAt,
    this.gradeBand,
  });

  factory SharedDeviceSession.fromJson(Map<String, dynamic> json) =>
      _$SharedDeviceSessionFromJson(json);

  Map<String, dynamic> toJson() => _$SharedDeviceSessionToJson(this);
}

/// Result of learner PIN validation on shared device
@JsonSerializable()
class SharedPinValidationResult {
  final bool valid;
  final String? sessionToken;
  final String? errorMessage;
  final int? remainingAttempts;

  SharedPinValidationResult({
    required this.valid,
    this.sessionToken,
    this.errorMessage,
    this.remainingAttempts,
  });

  factory SharedPinValidationResult.fromJson(Map<String, dynamic> json) =>
      _$SharedPinValidationResultFromJson(json);

  Map<String, dynamic> toJson() => _$SharedPinValidationResultToJson(this);
}

/// State for shared device mode controller
class SharedDeviceState {
  final DeviceMode mode;
  final bool isLoading;
  final String? error;
  final ClassroomRoster? roster;
  final SharedDeviceSession? activeSession;
  final RosterLearner? selectedLearner;

  const SharedDeviceState({
    this.mode = DeviceMode.personal,
    this.isLoading = false,
    this.error,
    this.roster,
    this.activeSession,
    this.selectedLearner,
  });

  SharedDeviceState copyWith({
    DeviceMode? mode,
    bool? isLoading,
    String? error,
    ClassroomRoster? roster,
    SharedDeviceSession? activeSession,
    RosterLearner? selectedLearner,
    bool clearError = false,
    bool clearRoster = false,
    bool clearSession = false,
    bool clearSelectedLearner = false,
  }) {
    return SharedDeviceState(
      mode: mode ?? this.mode,
      isLoading: isLoading ?? this.isLoading,
      error: clearError ? null : (error ?? this.error),
      roster: clearRoster ? null : (roster ?? this.roster),
      activeSession: clearSession ? null : (activeSession ?? this.activeSession),
      selectedLearner: clearSelectedLearner ? null : (selectedLearner ?? this.selectedLearner),
    );
  }

  bool get isSharedMode => mode == DeviceMode.shared;
  bool get hasActiveSession => activeSession != null;
  bool get hasRoster => roster != null;
  String? get currentLearnerId => activeSession?.learnerId;
}
