"""Schemas module for Writing Assessment Service."""

from app.schemas.requests import (
    FullAssessmentRequest,
    FullAssessmentResponse,
    GrammarCheckRequest,
    GrammarCheckResponse,
    ReadabilityRequest,
    ReadabilityResponse,
    FeedbackRequest,
    WritingFeedback,
    HolisticScore,
    TraitScores,
    TraitScore,
    GrammarReport,
    GrammarError,
    CoherenceAnalysis,
    LocalCoherence,
    GlobalCoherence,
    WeakTransition,
    TransitionAnalysis,
    StyleReport,
    VocabularyLevel,
    OverusedWord,
    ReadabilityProfile,
    ComplexityFactor,
    FeedbackPoint,
    Suggestion,
)

__all__ = [
    "FullAssessmentRequest",
    "FullAssessmentResponse",
    "GrammarCheckRequest",
    "GrammarCheckResponse",
    "ReadabilityRequest",
    "ReadabilityResponse",
    "FeedbackRequest",
    "WritingFeedback",
    "HolisticScore",
    "TraitScores",
    "TraitScore",
    "GrammarReport",
    "GrammarError",
    "CoherenceAnalysis",
    "LocalCoherence",
    "GlobalCoherence",
    "WeakTransition",
    "TransitionAnalysis",
    "StyleReport",
    "VocabularyLevel",
    "OverusedWord",
    "ReadabilityProfile",
    "ComplexityFactor",
    "FeedbackPoint",
    "Suggestion",
]
