import { Role } from './roles.js';

export enum Permission {
  TenantRead = 'tenant:read',
  TenantManage = 'tenant:manage',
  SchoolManage = 'school:manage',
  ClassroomManage = 'classroom:manage',
  UserManage = 'user:manage',
  // Content permissions
  ContentCreate = 'content:create',
  ContentEdit = 'content:edit',
  ContentReview = 'content:review',
  ContentPublish = 'content:publish',
  ContentAdmin = 'content:admin',
  // IEP & student permissions (PRD Phase 1)
  StudentRead = 'student:read',
  StudentCreate = 'student:create',
  StudentManage = 'student:manage',
  IepRead = 'iep:read',
  IepCreate = 'iep:create',
  IepUpdate = 'iep:update',
  IepApprove = 'iep:approve',
  GoalRead = 'goal:read',
  GoalCreate = 'goal:create',
  GoalUpdate = 'goal:update',
  ProgressRead = 'progress:read',
  ProgressRecord = 'progress:record',
  // Messaging permissions
  MessageSend = 'message:send',
  MessageRead = 'message:read',
  // Report permissions
  ReportRead = 'report:read',
  ReportExport = 'report:export',
  // Compliance permissions
  ComplianceRead = 'compliance:read',
  ComplianceManage = 'compliance:manage',
  AuditRead = 'audit:read',
  AuditExport = 'audit:export',
}

export const rolePermissions: Record<Role, Permission[]> = {
  [Role.PLATFORM_ADMIN]: [
    Permission.TenantRead,
    Permission.TenantManage,
    Permission.SchoolManage,
    Permission.ClassroomManage,
    Permission.UserManage,
    Permission.ContentCreate,
    Permission.ContentEdit,
    Permission.ContentReview,
    Permission.ContentPublish,
    Permission.ContentAdmin,
    Permission.StudentRead,
    Permission.StudentCreate,
    Permission.StudentManage,
    Permission.IepRead,
    Permission.IepCreate,
    Permission.IepUpdate,
    Permission.IepApprove,
    Permission.GoalRead,
    Permission.GoalCreate,
    Permission.GoalUpdate,
    Permission.ProgressRead,
    Permission.ProgressRecord,
    Permission.MessageSend,
    Permission.MessageRead,
    Permission.ReportRead,
    Permission.ReportExport,
    Permission.ComplianceRead,
    Permission.ComplianceManage,
    Permission.AuditRead,
    Permission.AuditExport,
  ],
  [Role.DISTRICT_ADMIN]: [
    Permission.TenantRead,
    Permission.SchoolManage,
    Permission.ClassroomManage,
    Permission.UserManage,
    Permission.StudentRead,
    Permission.StudentCreate,
    Permission.StudentManage,
    Permission.IepRead,
    Permission.IepApprove,
    Permission.GoalRead,
    Permission.ProgressRead,
    Permission.ReportRead,
    Permission.ReportExport,
    Permission.ComplianceRead,
    Permission.ComplianceManage,
    Permission.AuditRead,
    Permission.AuditExport,
  ],
  [Role.SCHOOL_ADMIN]: [
    Permission.TenantRead,
    Permission.SchoolManage,
    Permission.ClassroomManage,
    Permission.UserManage,
    Permission.StudentRead,
    Permission.StudentCreate,
    Permission.StudentManage,
    Permission.IepRead,
    Permission.IepApprove,
    Permission.GoalRead,
    Permission.ProgressRead,
    Permission.ReportRead,
    Permission.ReportExport,
    Permission.ComplianceRead,
    Permission.AuditRead,
  ],
  [Role.DISTRICT_CONTENT_ADMIN]: [
    Permission.TenantRead,
    Permission.ContentCreate,
    Permission.ContentEdit,
    Permission.ContentReview,
    Permission.ContentPublish,
    Permission.ContentAdmin,
  ],
  [Role.CURRICULUM_AUTHOR]: [
    Permission.TenantRead,
    Permission.ContentCreate,
    Permission.ContentEdit,
  ],
  [Role.CURRICULUM_REVIEWER]: [Permission.TenantRead, Permission.ContentReview],
  [Role.SUPPORT]: [Permission.TenantRead, Permission.StudentRead, Permission.IepRead],
  [Role.TEACHER]: [
    Permission.ClassroomManage,
    Permission.StudentRead,
    Permission.StudentCreate,
    Permission.IepRead,
    Permission.IepCreate,
    Permission.IepUpdate,
    Permission.GoalRead,
    Permission.GoalCreate,
    Permission.GoalUpdate,
    Permission.ProgressRead,
    Permission.ProgressRecord,
    Permission.MessageSend,
    Permission.MessageRead,
    Permission.ReportRead,
  ],
  [Role.THERAPIST]: [
    Permission.ClassroomManage,
    Permission.StudentRead,
    Permission.IepRead,
    Permission.IepUpdate,
    Permission.GoalRead,
    Permission.GoalCreate,
    Permission.GoalUpdate,
    Permission.ProgressRead,
    Permission.ProgressRecord,
    Permission.MessageSend,
    Permission.MessageRead,
    Permission.ReportRead,
  ],
  [Role.LEARNER]: [
    Permission.ProgressRead,
    Permission.GoalRead,
  ],
  [Role.PARENT]: [
    Permission.IepRead,
    Permission.GoalRead,
    Permission.ProgressRead,
    Permission.MessageSend,
    Permission.MessageRead,
    Permission.ReportRead,
    Permission.ReportExport,
  ],
};

export function hasPermission(roles: Role[] | undefined, permission: Permission): boolean {
  if (!roles || roles.length === 0) return false;
  return roles.some((role) => rolePermissions[role]?.includes(permission));
}
