# .github/actions/deploy-k8s/action.yml
# Reusable action for deploying services to Kubernetes

name: Deploy to Kubernetes
description: Deploys services to a Kubernetes cluster using Kustomize

inputs:
  cluster:
    description: 'GKE cluster name'
    required: true
  zone:
    description: 'GKE zone/region'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  version:
    description: 'Image version tag'
    required: true
  services:
    description: 'Services to deploy (comma-separated, or "all")'
    required: false
    default: 'all'
  overlay:
    description: 'Kustomize overlay directory'
    required: false
    default: ''
  timeout:
    description: 'Rollout timeout in seconds'
    required: false
    default: '600'
  wait:
    description: 'Whether to wait for rollout'
    required: false
    default: 'true'

outputs:
  deployed-services:
    description: 'List of deployed services'
    value: ${{ steps.deploy.outputs.services }}

runs:
  using: composite
  steps:
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ inputs.cluster }}
        location: ${{ inputs.zone }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Determine overlay path
      id: overlay
      shell: bash
      env:
        INPUT_OVERLAY: ${{ inputs.overlay }}
        INPUT_NAMESPACE: ${{ inputs.namespace }}
      run: |
        if [[ -n "$INPUT_OVERLAY" ]]; then
          OVERLAY_PATH="$INPUT_OVERLAY"
        else
          OVERLAY_PATH="infra/k8s/overlays/$INPUT_NAMESPACE"
        fi
        echo "path=$OVERLAY_PATH" >> $GITHUB_OUTPUT

    - name: Determine services
      id: services
      shell: bash
      env:
        INPUT_SERVICES: ${{ inputs.services }}
      run: |
        if [[ "$INPUT_SERVICES" == "all" ]]; then
          SERVICES="auth-svc content-svc session-svc assessment-svc analytics-svc ai-orchestrator notify-svc messaging-svc goal-svc focus-svc personalization-svc billing-svc consent-svc"
        else
          SERVICES="$INPUT_SERVICES"
          SERVICES="${SERVICES//,/ }"
        fi
        echo "list=$SERVICES" >> $GITHUB_OUTPUT

    - name: Update image tags
      id: update
      shell: bash
      env:
        OVERLAY_PATH: ${{ steps.overlay.outputs.path }}
        SERVICES_LIST: ${{ steps.services.outputs.list }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        cd "$OVERLAY_PATH"
        
        for service in $SERVICES_LIST; do
          echo "Setting image for $service to version $INPUT_VERSION..."
          kustomize edit set image gcr.io/$PROJECT_ID/${service}=gcr.io/$PROJECT_ID/${service}:$INPUT_VERSION 2>/dev/null || echo "Skipping $service (not in kustomization)"
        done

    - name: Deploy to Kubernetes
      id: deploy
      shell: bash
      env:
        OVERLAY_PATH: ${{ steps.overlay.outputs.path }}
        SERVICES_LIST: ${{ steps.services.outputs.list }}
      run: |
        echo "::group::Applying manifests"
        kustomize build "$OVERLAY_PATH" | kubectl apply -f -
        echo "::endgroup::"
        
        echo "services=$SERVICES_LIST" >> $GITHUB_OUTPUT

    - name: Wait for rollout
      if: inputs.wait == 'true'
      shell: bash
      env:
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
      run: |
        echo "::group::Waiting for rollout"
        kubectl rollout status deployment --all -n $INPUT_NAMESPACE --timeout=${INPUT_TIMEOUT}s
        echo "::endgroup::"

    - name: Verify deployment
      shell: bash
      env:
        INPUT_NAMESPACE: ${{ inputs.namespace }}
      run: |
        echo "::group::Deployment Status"
        kubectl get deployments -n $INPUT_NAMESPACE
        echo "::endgroup::"
        
        echo "::group::Pod Status"
        kubectl get pods -n $INPUT_NAMESPACE
        echo "::endgroup::"
