/**
 * Types for the HOMEWORK_HELPER agent contract with AI Orchestrator.
 *
 * The Homework Helper agent produces step-by-step scaffolding questions
 * that guide the learner toward understanding WITHOUT giving direct answers.
 */

// ══════════════════════════════════════════════════════════════════════════════
// REQUEST TYPES
// ══════════════════════════════════════════════════════════════════════════════

export type Subject = 'ELA' | 'MATH' | 'SCIENCE' | 'OTHER';
export type GradeBand = 'K5' | 'G6_8' | 'G9_12';

/**
 * Guardrail configuration passed to the AI agent.
 * These constraints are enforced both in the prompt and post-processing.
 */
export interface HomeworkGuardrails {
  /** Never provide direct numerical or factual answers */
  noDirectAnswers: boolean;

  /** Maximum number of hints per step */
  maxHintsPerStep: number;

  /** Encourage showing work/reasoning */
  requireWorkShown: boolean;

  /** Age-appropriate vocabulary level */
  vocabularyLevel: GradeBand;
}

/**
 * Request payload sent to the HOMEWORK_HELPER agent.
 */
export interface HomeworkHelperRequest {
  /** Academic subject area */
  subject: Subject;

  /** Grade band for age-appropriate scaffolding */
  gradeBand: GradeBand;

  /** The raw homework problem text (from OCR or direct input) */
  rawText: string;

  /** Maximum number of scaffolding steps to generate */
  maxSteps: number;

  /** Guardrail configuration */
  guardrails: HomeworkGuardrails;

  /** Optional: previous context for follow-up questions */
  previousContext?: PreviousStepContext[];
}

/**
 * Context from previous steps for follow-up scaffolding.
 */
export interface PreviousStepContext {
  stepOrder: number;
  promptText: string;
  learnerResponse?: string;
  wasCorrect?: boolean;
}

// ══════════════════════════════════════════════════════════════════════════════
// RESPONSE TYPES
// ══════════════════════════════════════════════════════════════════════════════

/**
 * A single scaffolding step generated by the AI.
 */
export interface GeneratedStep {
  /** Order in the sequence (1-based) */
  stepOrder: number;

  /** The scaffolding prompt to present to the learner */
  promptText: string;

  /** Optional hint that can be revealed if needed */
  hintText?: string;

  /** Expected concept/approach (for teacher review, not shown to learner) */
  expectedConcept?: string;
}

/**
 * Response from the HOMEWORK_HELPER agent.
 */
export interface HomeworkHelperResponse {
  /** Generated scaffolding steps */
  steps: GeneratedStep[];

  /** Detected problem type/category */
  problemType?: string;

  /** Any warnings about the content (e.g., unclear problem statement) */
  warnings?: string[];

  /** Whether guardrails were triggered and content was modified */
  guardrailsApplied?: boolean;
}

// ══════════════════════════════════════════════════════════════════════════════
// AI ORCHESTRATOR REQUEST WRAPPER
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Full request to AI Orchestrator internal API.
 */
export interface AiOrchestratorRequest {
  tenantId: string;
  agentType: 'HOMEWORK_HELPER';
  payload: HomeworkHelperRequest;
  metadata?: {
    correlationId?: string;
    learnerId?: string;
    sessionId?: string;
  };
}

/**
 * Response from AI Orchestrator internal API.
 */
export interface AiOrchestratorResponse {
  content: HomeworkHelperResponse;
  tokensUsed: number;
  tokensPrompt?: number;
  tokensCompletion?: number;
  metadata?: Record<string, unknown>;
}

// ══════════════════════════════════════════════════════════════════════════════
// FEEDBACK REQUEST/RESPONSE (for step answer evaluation)
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Request payload for evaluating a learner's step response.
 */
export interface StepFeedbackRequest {
  subject: Subject;
  gradeBand: GradeBand;

  /** The original homework problem */
  originalProblem: string;

  /** The current step's scaffolding prompt */
  stepPrompt: string;

  /** The learner's response to evaluate */
  learnerResponse: string;

  /** Expected concept for this step */
  expectedConcept?: string;

  /** Guardrails for feedback generation */
  guardrails: HomeworkGuardrails;
}

/**
 * Response from step feedback evaluation.
 */
export interface StepFeedbackResponse {
  /** AI-generated scaffolding feedback */
  feedback: string;

  /** Whether the response demonstrates understanding */
  demonstratesUnderstanding: boolean;

  /** Suggested next action */
  nextAction: 'proceed' | 'retry' | 'hint';

  /** Whether guardrails were triggered */
  guardrailsApplied?: boolean;
}
