/**
 * GET /api/dashboard/alerts
 *
 * Returns list of platform alerts for the admin dashboard.
 * POST /api/dashboard/alerts - Not needed, alerts are generated by the system
 */

import { NextRequest, NextResponse } from 'next/server';
import { requirePlatformAdmin } from '@/lib/auth';
import { listAlerts, listActiveAlerts, type AlertFilters } from '@/lib/api/alerts.api';

export async function GET(request: NextRequest) {
  try {
    const session = await requirePlatformAdmin();

    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status');

    const accessToken = (session as { accessToken?: string })?.accessToken || '';

    // If requesting only active alerts, use the optimized endpoint
    if (status === 'active') {
      const alerts = await listActiveAlerts(accessToken);
      return NextResponse.json(alerts);
    }

    // Build filters object conditionally to avoid undefined values
    const filters: AlertFilters = {};
    const severity = searchParams.get('severity') as 'critical' | 'warning' | 'info' | null;
    const source = searchParams.get('source');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const page = searchParams.get('page');
    const pageSize = searchParams.get('pageSize');
    
    if (severity) filters.severity = severity;
    if (status) filters.status = status as 'active' | 'acknowledged' | 'resolved' | 'silenced';
    if (source) filters.source = source;
    if (startDate) filters.since = new Date(startDate);
    if (endDate) filters.until = new Date(endDate);

    const response = await listAlerts(accessToken, filters, page ? parseInt(page) : 1, pageSize ? parseInt(pageSize) : 50);

    return NextResponse.json(response);
  } catch (error) {
    console.error('Failed to fetch alerts:', error);
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    return NextResponse.json(
      { error: 'Failed to fetch alerts' },
      { status: 500 }
    );
  }
}
