import type { OnboardingFlow } from '../types.js';

export const districtAdminFlow: OnboardingFlow = {
  id: 'district_admin',
  title: 'District Admin Setup',
  description: 'Complete these steps to get your district fully configured on Aivo.',
  role: 'district_admin',
  completionRoute: '/dashboard',
  completionMessage: "Congratulations! Your district is fully set up. You're ready to empower your schools with Aivo.",
  steps: [
    {
      id: 'da_welcome',
      title: 'Welcome & Overview',
      description: 'Learn about the district admin dashboard and key features available to you.',
      icon: 'sparkles',
      completionKey: 'da_welcome_viewed',
      estimatedTime: '1 min',
    },
    {
      id: 'da_branding',
      title: 'Customize Branding',
      description: 'Upload your district logo and set brand colors to personalize the experience.',
      icon: 'palette',
      targetRoute: '/settings/branding',
      completionKey: 'da_branding_set',
      estimatedTime: '3 min',
      skippable: true,
    },
    {
      id: 'da_sso',
      title: 'Configure SSO',
      description: 'Set up Single Sign-On so teachers and students can log in with their existing credentials.',
      icon: 'shield',
      targetRoute: '/settings/sso',
      completionKey: 'da_sso_configured',
      estimatedTime: '5 min',
      helpText: 'You can use Google, Microsoft, or Clever SSO.',
    },
    {
      id: 'da_sis',
      title: 'Connect SIS',
      description: 'Import your Student Information System data to automatically roster schools, classes, and students.',
      icon: 'database',
      targetRoute: '/integrations/sis',
      completionKey: 'da_sis_connected',
      estimatedTime: '10 min',
      skippable: true,
      helpText: 'Supports OneRoster CSV, OneRoster API, and SFTP upload.',
    },
    {
      id: 'da_schools',
      title: 'Add Schools',
      description: 'Create or verify your schools in the system. Schools imported via SIS will appear automatically.',
      icon: 'building',
      targetRoute: '/schools',
      completionKey: 'da_schools_added',
      estimatedTime: '5 min',
    },
    {
      id: 'da_privacy',
      title: 'Review Privacy Settings',
      description: 'Configure data retention, consent requirements, and privacy policies for your district.',
      icon: 'lock',
      targetRoute: '/privacy',
      completionKey: 'da_privacy_reviewed',
      estimatedTime: '3 min',
    },
    {
      id: 'da_invite_teachers',
      title: 'Invite Teachers',
      description: 'Send invitations to teachers so they can start creating content and managing their classrooms.',
      icon: 'user-plus',
      targetRoute: '/schools',
      completionKey: 'da_teachers_invited',
      estimatedTime: '5 min',
    },
    {
      id: 'da_explore',
      title: 'Explore Analytics',
      description: 'Take a tour of the analytics dashboard to understand how you can track learning outcomes.',
      icon: 'bar-chart',
      targetRoute: '/analytics',
      completionKey: 'da_analytics_explored',
      estimatedTime: '2 min',
      skippable: true,
    },
  ],
};
