import type { OnboardingFlow } from '../types.js';

export const parentFlow: OnboardingFlow = {
  id: 'parent',
  title: 'Parent Welcome Guide',
  description: "Get started with Aivo and stay connected to your child's learning journey.",
  role: 'parent',
  completionRoute: '/dashboard',
  completionMessage: "You're all set! You can now track your child's progress and stay engaged with their learning.",
  steps: [
    {
      id: 'parent_welcome',
      title: 'Welcome to Aivo',
      description: "Learn how Aivo helps your child learn and how you can stay involved in their education.",
      icon: 'sparkles',
      completionKey: 'parent_welcome_viewed',
      estimatedTime: '2 min',
    },
    {
      id: 'parent_link_child',
      title: 'Link Your Child',
      description: "Enter the code provided by your child's school or teacher to link your account.",
      icon: 'link',
      targetRoute: '/children/link',
      completionKey: 'parent_child_linked',
      estimatedTime: '2 min',
      helpText: "Check your email or ask your child's teacher for the linking code.",
    },
    {
      id: 'parent_notifications',
      title: 'Set Up Notifications',
      description: 'Choose how and when you want to be notified about your child\'s progress and school updates.',
      icon: 'bell',
      targetRoute: '/settings/notifications',
      completionKey: 'parent_notifications_set',
      estimatedTime: '2 min',
      skippable: true,
    },
    {
      id: 'parent_progress',
      title: 'Explore Progress Dashboard',
      description: "See your child's learning progress, strengths, and areas for improvement at a glance.",
      icon: 'bar-chart',
      targetRoute: '/dashboard',
      completionKey: 'parent_progress_explored',
      estimatedTime: '3 min',
    },
    {
      id: 'parent_goals',
      title: 'Set Learning Goals',
      description: 'Work with your child to set personalized learning goals and track milestones together.',
      icon: 'target',
      targetRoute: '/goals',
      completionKey: 'parent_goals_set',
      estimatedTime: '3 min',
      skippable: true,
    },
  ],
};
