#!/usr/bin/env bash
# =============================================================================
# Generate ExternalSecret manifests for all deployed services
# =============================================================================
# Reads the service→database mapping and generates per-namespace manifests
# for both staging and production.
#
# Usage:
#   ./scripts/generate-external-secrets.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ─── Service → Vault database property mapping ────────────────────────────
# Format: "service-name:vault_db_property"
SERVICES=(
  "auth-svc:auth_url"
  "api-gateway:auth_url"
  "tenant-svc:tenant_url"
  "profile-svc:auth_url"
  "session-svc:session_url"
  "content-svc:content_url"
  "assessment-svc:assessment_url"
  "analytics-svc:analytics_url"
  "billing-svc:billing_url"
  "gamification-svc:auth_url"
  "parent-svc:auth_url"
  "messaging-svc:auth_url"
  "audit-svc:auth_url"
  "notify-svc:auth_url"
  "reports-svc:analytics_url"
  "realtime-svc:auth_url"
  "compliance-svc:auth_url"
  "sis-sync-svc:auth_url"
  "iep-svc:auth_url"
)

# ─── Services that also need Stripe secrets ────────────────────────────────
STRIPE_SERVICES=("billing-svc" "payments-svc")

# ─── Services that also need AI provider secrets ───────────────────────────
AI_SERVICES=(
  "ai-orchestrator" "brain-engine" "ai-inference-svc"
  "training-svc" "ml-recommendation-svc"
)

# ─── Services that also need S3 / storage secrets ─────────────────────────
STORAGE_SERVICES=("content-svc" "coursework-ingest-svc" "document-intelligence-svc")

# ─── Generate manifest for one service in one namespace ────────────────────
generate_manifest() {
  local svc="$1"
  local db_key="$2"
  local ns="$3"
  local outdir="${REPO_ROOT}/infra/k8s/overlays/${ns}/external-secrets"
  local outfile="${outdir}/${svc}.yaml"

  mkdir -p "${outdir}"

  # Start with base data entries
  local extra_data=""

  # Add Stripe secrets if applicable
  for stripe_svc in "${STRIPE_SERVICES[@]}"; do
    if [[ "$svc" == "$stripe_svc" ]]; then
      extra_data="${extra_data}
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: secret/aivo/stripe
        property: secret_key
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: secret/aivo/stripe
        property: webhook_secret"
      break
    fi
  done

  # Add AI provider secrets if applicable
  for ai_svc in "${AI_SERVICES[@]}"; do
    if [[ "$svc" == "$ai_svc" ]]; then
      extra_data="${extra_data}
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/aivo/ai-providers
        property: openai_api_key
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: secret/aivo/ai-providers
        property: anthropic_api_key"
      break
    fi
  done

  # Add S3 secrets if applicable
  for storage_svc in "${STORAGE_SERVICES[@]}"; do
    if [[ "$svc" == "$storage_svc" ]]; then
      extra_data="${extra_data}
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/aivo/storage
        property: aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/aivo/storage
        property: aws_secret_access_key
    - secretKey: S3_BUCKET
      remoteRef:
        key: secret/aivo/storage
        property: s3_bucket"
      break
    fi
  done

  cat > "${outfile}" << EOF
# Auto-generated by scripts/generate-external-secrets.sh — do not edit manually
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${svc}-secrets
  namespace: ${ns}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ${svc}-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: secret/aivo/auth
        property: jwt_public_key
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: secret/aivo/auth
        property: internal_api_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/aivo/database
        property: ${db_key}
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/aivo/redis
        property: url
    - secretKey: NATS_URL
      remoteRef:
        key: secret/aivo/nats
        property: url${extra_data}
EOF
}

# ─── Main ──────────────────────────────────────────────────────────────────
echo "=== Generating ExternalSecret manifests ==="

for entry in "${SERVICES[@]}"; do
  IFS=':' read -r svc db_key <<< "$entry"

  for ns in aivo-staging aivo-prod; do
    generate_manifest "$svc" "$db_key" "$ns"
  done
done

COUNT=${#SERVICES[@]}
echo "Generated ExternalSecret manifests for ${COUNT} services × 2 namespaces"
echo "Output: infra/k8s/overlays/{aivo-staging,aivo-prod}/external-secrets/"
