# .github/actions/run-tests/action.yml
# Reusable action for running tests with various configurations

name: Run Tests
description: Runs tests with database services and coverage

inputs:
  test-command:
    description: 'Test command to run'
    required: false
    default: 'pnpm run test'
  coverage:
    description: 'Whether to collect coverage'
    required: false
    default: 'true'
  shard:
    description: 'Test shard (e.g., "1/4")'
    required: false
    default: ''
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

outputs:
  coverage-file:
    description: 'Path to coverage file'
    value: ${{ steps.test.outputs.coverage-file }}

runs:
  using: composite
  steps:
    - name: Run tests
      id: test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_ENV: test
        CI: true
        INPUT_TEST_COMMAND: ${{ inputs.test-command }}
        INPUT_SHARD: ${{ inputs.shard }}
        INPUT_COVERAGE: ${{ inputs.coverage }}
      run: |
        CMD="$INPUT_TEST_COMMAND"
        
        if [[ -n "$INPUT_SHARD" ]]; then
          CMD="$CMD --shard=$INPUT_SHARD"
        fi
        
        if [[ "$INPUT_COVERAGE" == "true" ]]; then
          CMD="$CMD --coverage"
        fi
        
        echo "Running: $CMD"
        $CMD
        
        if [[ -f "coverage/lcov.info" ]]; then
          echo "coverage-file=coverage/lcov.info" >> $GITHUB_OUTPUT
        fi

    - name: Upload coverage
      if: inputs.coverage == 'true'
      uses: codecov/codecov-action@v3
      with:
        files: ${{ inputs.working-directory }}/coverage/lcov.info
        fail_ci_if_error: false
