/**
 * Standard attribute names for Aivo observability
 *
 * These constants ensure consistent naming across all services
 * for traces, metrics, and logs.
 */
export declare const AIVO_ATTRIBUTES: {
    readonly SERVICE_NAME: "service.name";
    readonly TENANT_ID: "aivo.tenant_id";
    readonly USER_ID: "aivo.user_id";
    readonly LEARNER_ID: "aivo.learner_id";
    readonly REQUEST_ID: "aivo.request_id";
    readonly CORRELATION_ID: "aivo.correlation_id";
    readonly HTTP_METHOD: "http.method";
    readonly HTTP_ROUTE: "http.route";
    readonly HTTP_STATUS_CODE: "http.status_code";
    readonly HTTP_URL: "http.url";
    readonly HTTP_TARGET: "http.target";
    readonly HTTP_HOST: "http.host";
    readonly HTTP_USER_AGENT: "http.user_agent";
    readonly AI_AGENT_TYPE: "aivo.ai.agent_type";
    readonly AI_PROVIDER: "aivo.ai.provider";
    readonly AI_MODEL: "aivo.ai.model";
    readonly AI_TOKENS_INPUT: "aivo.ai.tokens_input";
    readonly AI_TOKENS_OUTPUT: "aivo.ai.tokens_output";
    readonly AI_TOKENS_TOTAL: "aivo.ai.tokens_total";
    readonly AI_COST_USD: "aivo.ai.cost_usd";
    readonly AI_FAILOVER_FROM: "aivo.ai.failover_from";
    readonly AI_FAILOVER_TO: "aivo.ai.failover_to";
    readonly AI_SAFETY_STATUS: "aivo.ai.safety_status";
    readonly AI_SAFETY_REASON: "aivo.ai.safety_reason";
    readonly SESSION_ID: "aivo.session.id";
    readonly SESSION_TYPE: "aivo.session.type";
    readonly SESSION_SUBJECT: "aivo.session.subject";
    readonly SESSION_GRADE: "aivo.session.grade";
    readonly FOCUS_INTERVENTION_TYPE: "aivo.focus.intervention_type";
    readonly FOCUS_SCORE_BEFORE: "aivo.focus.score_before";
    readonly FOCUS_SCORE_AFTER: "aivo.focus.score_after";
    readonly RECOMMENDATION_ID: "aivo.recommendation.id";
    readonly RECOMMENDATION_TYPE: "aivo.recommendation.type";
    readonly RECOMMENDATION_STATUS: "aivo.recommendation.status";
    readonly ERROR_TYPE: "error.type";
    readonly ERROR_MESSAGE: "error.message";
    readonly EXCEPTION_STACKTRACE: "exception.stacktrace";
};
export declare const METRIC_NAMES: {
    readonly HTTP_REQUEST_DURATION: "aivo_http_request_duration_seconds";
    readonly HTTP_REQUESTS_TOTAL: "aivo_http_requests_total";
    readonly HTTP_REQUEST_SIZE: "aivo_http_request_size_bytes";
    readonly HTTP_RESPONSE_SIZE: "aivo_http_response_size_bytes";
    readonly HTTP_ACTIVE_REQUESTS: "aivo_http_active_requests";
    readonly AI_REQUEST_DURATION: "aivo_ai_request_duration_seconds";
    readonly AI_REQUESTS_TOTAL: "aivo_ai_requests_total";
    readonly AI_TOKENS_TOTAL: "aivo_ai_tokens_total";
    readonly AI_COST_USD_TOTAL: "aivo_ai_cost_usd_total";
    readonly AI_FAILOVER_TOTAL: "aivo_ai_failover_total";
    readonly AI_SAFETY_BLOCKS_TOTAL: "aivo_ai_safety_blocks_total";
    readonly AI_ERRORS_TOTAL: "aivo_ai_errors_total";
    readonly SESSIONS_STARTED_TOTAL: "aivo_sessions_started_total";
    readonly SESSIONS_COMPLETED_TOTAL: "aivo_sessions_completed_total";
    readonly SESSIONS_ABANDONED_TOTAL: "aivo_sessions_abandoned_total";
    readonly SESSION_DURATION_SECONDS: "aivo_session_duration_seconds";
    readonly SESSIONS_ACTIVE: "aivo_sessions_active";
    readonly FOCUS_INTERVENTIONS_TOTAL: "aivo_focus_interventions_total";
    readonly FOCUS_SCORE: "aivo_focus_score";
    readonly FOCUS_INTERVENTION_EFFECTIVENESS: "aivo_focus_intervention_effectiveness";
    readonly RECOMMENDATIONS_CREATED_TOTAL: "aivo_recommendations_created_total";
    readonly RECOMMENDATIONS_ACCEPTED_TOTAL: "aivo_recommendations_accepted_total";
    readonly RECOMMENDATIONS_DECLINED_TOTAL: "aivo_recommendations_declined_total";
    readonly RECOMMENDATIONS_EXPIRED_TOTAL: "aivo_recommendations_expired_total";
    readonly AUTH_REQUESTS_TOTAL: "aivo_auth_requests_total";
    readonly AUTH_FAILURES_TOTAL: "aivo_auth_failures_total";
    readonly AUTH_TOKEN_REFRESHES_TOTAL: "aivo_auth_token_refreshes_total";
    readonly EVENTS_PUBLISHED_TOTAL: "aivo_events_published_total";
    readonly EVENTS_PROCESSED_TOTAL: "aivo_events_processed_total";
    readonly EVENTS_FAILED_TOTAL: "aivo_events_failed_total";
    readonly EVENTS_DLQ_DEPTH: "aivo_events_dlq_depth";
    readonly EVENT_PROCESSING_DURATION: "aivo_event_processing_duration_seconds";
    readonly DB_QUERY_DURATION: "aivo_db_query_duration_seconds";
    readonly DB_CONNECTIONS_ACTIVE: "aivo_db_connections_active";
    readonly DB_CONNECTIONS_IDLE: "aivo_db_connections_idle";
    readonly DB_CONNECTIONS_WAITING: "aivo_db_connections_waiting";
};
export declare const METRIC_LABELS: {
    readonly SERVICE: "service";
    readonly ENVIRONMENT: "environment";
    readonly TENANT_ID: "tenant_id";
    readonly METHOD: "method";
    readonly ROUTE: "route";
    readonly STATUS_CODE: "status_code";
    readonly STATUS_CLASS: "status_class";
    readonly AGENT_TYPE: "agent_type";
    readonly PROVIDER: "provider";
    readonly MODEL: "model";
    readonly TOKEN_TYPE: "token_type";
    readonly SAFETY_STATUS: "safety_status";
    readonly SAFETY_REASON: "safety_reason";
    readonly FAILOVER_FROM: "failover_from";
    readonly FAILOVER_TO: "failover_to";
    readonly SESSION_TYPE: "session_type";
    readonly SUBJECT: "subject";
    readonly GRADE: "grade";
    readonly COMPLETION_STATUS: "completion_status";
    readonly INTERVENTION_TYPE: "intervention_type";
    readonly EFFECTIVENESS: "effectiveness";
    readonly RECOMMENDATION_TYPE: "recommendation_type";
    readonly AUTH_METHOD: "auth_method";
    readonly FAILURE_REASON: "failure_reason";
    readonly EVENT_TYPE: "event_type";
    readonly EVENT_SOURCE: "event_source";
};
export declare const HISTOGRAM_BUCKETS: {
    HTTP_DURATION: number[];
    AI_DURATION: number[];
    SESSION_DURATION: number[];
    EVENT_DURATION: number[];
    DB_DURATION: number[];
    SIZE_BYTES: number[];
};
export declare const SERVICE_NAMES: {
    readonly AI_ORCHESTRATOR: "ai-orchestrator";
    readonly AUTH_SVC: "auth-svc";
    readonly SESSION_SVC: "session-svc";
    readonly FOCUS_SVC: "focus-svc";
    readonly LEARNER_SVC: "learner-svc";
    readonly GOAL_SVC: "goal-svc";
    readonly BILLING_SVC: "billing-svc";
    readonly PAYMENTS_SVC: "payments-svc";
    readonly NOTIFY_SVC: "notify-svc";
    readonly MESSAGING_SVC: "messaging-svc";
    readonly CONTENT_SVC: "content-svc";
    readonly ANALYTICS_SVC: "analytics-svc";
    readonly REPORTS_SVC: "reports-svc";
    readonly BASELINE_SVC: "baseline-svc";
    readonly ASSESSMENT_SVC: "assessment-svc";
    readonly PERSONALIZATION_SVC: "personalization-svc";
    readonly KONG_GATEWAY: "kong-gateway";
    readonly APOLLO_ROUTER: "apollo-router";
};
//# sourceMappingURL=constants.d.ts.map