/**
 * Mock Data for Teacher Dashboard
 *
 * Development data for testing dashboard components
 */

import type {
  Class,
  Student,
  ClassEnrollment,
  DashboardStats,
  DashboardData,
  InterventionAlert,
  RecentActivityItem,
  UpcomingLesson,
  UpcomingEvent,
  ClassPerformanceData,
} from './types';

// Mock Students
export const mockStudents: Student[] = [
  {
    id: 'student-1',
    name: 'Emma Wilson',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@school.edu',
    gradeLevel: '6',
    averageScore: 92,
    progressPercentage: 78,
    assignmentsCompleted: 18,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    engagementLevel: 'high',
    hasIep: false,
    has504: false,
    riskLevel: 'none',
  },
  {
    id: 'student-2',
    name: 'Alex Smith',
    firstName: 'Alex',
    lastName: 'Smith',
    gradeLevel: '6',
    averageScore: 75,
    progressPercentage: 62,
    assignmentsCompleted: 14,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    engagementLevel: 'medium',
    hasIep: true,
    has504: false,
    riskLevel: 'low',
    iepDetails: {
      id: 'iep-1',
      studentId: 'student-2',
      status: 'active',
      startDate: '2025-09-01',
      endDate: '2026-08-31',
      nextReviewDate: '2026-02-15',
      eligibilityCategory: 'Specific Learning Disability',
      primaryDisability: 'Reading Comprehension',
      caseManager: 'Mrs. Johnson',
      goals: [
        {
          id: 'goal-1',
          domain: 'Reading',
          description: 'Improve reading comprehension to grade level',
          baseline: 'Currently reading at 4th grade level',
          targetDate: '2026-05-01',
          measurementMethod: 'Weekly assessments',
          currentProgress: 65,
          targetProgress: 100,
          status: 'on_track',
          objectives: [],
          progressNotes: [],
        },
        {
          id: 'goal-2',
          domain: 'Writing',
          description: 'Write organized paragraphs with topic sentences',
          baseline: 'Writes 2-3 sentences without structure',
          targetDate: '2026-05-01',
          measurementMethod: 'Monthly writing samples',
          currentProgress: 45,
          targetProgress: 100,
          status: 'at_risk',
          objectives: [],
          progressNotes: [],
        },
      ],
      services: [
        {
          id: 'service-1',
          serviceType: 'Resource Room',
          provider: 'Special Education Teacher',
          frequency: '5x weekly',
          duration: '45 minutes',
          location: 'Resource Room',
          startDate: '2025-09-01',
          endDate: '2026-06-15',
        },
      ],
      lastModified: '2025-12-15',
    },
    accommodations: [
      {
        id: 'acc-1',
        category: 'presentation',
        description: 'Text-to-speech for reading passages',
        isCritical: true,
        implementationStatus: 'active',
      },
      {
        id: 'acc-2',
        category: 'timing',
        description: 'Extended time (1.5x) on tests',
        isCritical: true,
        implementationStatus: 'active',
      },
      {
        id: 'acc-3',
        category: 'setting',
        description: 'Preferential seating near teacher',
        isCritical: false,
        implementationStatus: 'active',
      },
    ],
    parentContacts: [
      {
        id: 'parent-1',
        name: 'Sarah Smith',
        relationship: 'mother',
        email: 'sarah.smith@email.com',
        phone: '555-0123',
        isPrimary: true,
        preferredContactMethod: 'email',
      },
    ],
  },
  {
    id: 'student-3',
    name: 'Jordan Lee',
    firstName: 'Jordan',
    lastName: 'Lee',
    gradeLevel: '6',
    averageScore: 68,
    progressPercentage: 45,
    assignmentsCompleted: 10,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    engagementLevel: 'low',
    hasIep: false,
    has504: true,
    riskLevel: 'medium',
    plan504Details: {
      id: '504-1',
      studentId: 'student-3',
      status: 'active',
      startDate: '2025-09-01',
      endDate: '2026-06-15',
      nextReviewDate: '2026-03-01',
      disablingCondition: 'ADHD',
      accommodations: [],
      lastModified: '2025-11-01',
    },
    accommodations: [
      {
        id: 'acc-4',
        category: 'setting',
        description: 'Seat away from distractions',
        isCritical: true,
        implementationStatus: 'active',
      },
      {
        id: 'acc-5',
        category: 'timing',
        description: 'Frequent breaks during long assignments',
        isCritical: false,
        implementationStatus: 'active',
      },
    ],
    riskFactors: [
      {
        id: 'risk-1',
        type: 'engagement',
        description: 'Low engagement in class activities',
        severity: 'medium',
        detectedAt: '2026-01-10',
        indicators: ['Missed 3 assignments', 'Low participation'],
      },
    ],
  },
  {
    id: 'student-4',
    name: 'Michael Davis',
    firstName: 'Michael',
    lastName: 'Davis',
    gradeLevel: '6',
    averageScore: 58,
    progressPercentage: 35,
    assignmentsCompleted: 8,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    engagementLevel: 'low',
    hasIep: false,
    has504: false,
    riskLevel: 'high',
    riskFactors: [
      {
        id: 'risk-2',
        type: 'academic',
        description: '3 missing assignments this week',
        severity: 'high',
        detectedAt: '2026-01-15',
        indicators: ['Failing quiz scores', 'Incomplete homework'],
      },
      {
        id: 'risk-3',
        type: 'attendance',
        description: 'Multiple absences in past 2 weeks',
        severity: 'medium',
        detectedAt: '2026-01-12',
        indicators: ['3 absences', '2 tardies'],
      },
    ],
    interventions: [
      {
        id: 'int-1',
        studentId: 'student-4',
        type: 'academic',
        title: 'After-school tutoring',
        description: 'Weekly tutoring sessions for math concepts',
        status: 'in_progress',
        startDate: '2026-01-10',
        responsibleParty: 'Math Department',
        goals: ['Improve quiz scores', 'Complete missing assignments'],
        progress: 25,
        notes: [],
      },
    ],
  },
  {
    id: 'student-5',
    name: 'Sophia Martinez',
    firstName: 'Sophia',
    lastName: 'Martinez',
    gradeLevel: '6',
    averageScore: 88,
    progressPercentage: 85,
    assignmentsCompleted: 19,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    engagementLevel: 'high',
    hasIep: false,
    has504: false,
    riskLevel: 'none',
  },
  {
    id: 'student-6',
    name: 'Liam Chen',
    firstName: 'Liam',
    lastName: 'Chen',
    gradeLevel: '6',
    averageScore: 95,
    progressPercentage: 92,
    assignmentsCompleted: 20,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    engagementLevel: 'high',
    hasIep: false,
    has504: false,
    riskLevel: 'none',
  },
  {
    id: 'student-7',
    name: 'Taylor Brown',
    firstName: 'Taylor',
    lastName: 'Brown',
    gradeLevel: '6',
    averageScore: 82,
    progressPercentage: 70,
    assignmentsCompleted: 16,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    engagementLevel: 'medium',
    hasIep: true,
    has504: false,
    riskLevel: 'none',
    iepDetails: {
      id: 'iep-2',
      studentId: 'student-7',
      status: 'active',
      startDate: '2025-09-01',
      endDate: '2026-08-31',
      nextReviewDate: '2026-02-28',
      eligibilityCategory: 'Speech or Language Impairment',
      caseManager: 'Mrs. Anderson',
      goals: [
        {
          id: 'goal-3',
          domain: 'Speech',
          description: 'Improve articulation of R and L sounds',
          baseline: '60% accuracy',
          targetDate: '2026-05-01',
          measurementMethod: 'Speech therapy assessments',
          currentProgress: 85,
          targetProgress: 100,
          status: 'on_track',
          objectives: [],
          progressNotes: [],
        },
      ],
      services: [
        {
          id: 'service-2',
          serviceType: 'Speech Therapy',
          provider: 'Speech-Language Pathologist',
          frequency: '2x weekly',
          duration: '30 minutes',
          location: 'Speech Room',
          startDate: '2025-09-01',
          endDate: '2026-06-15',
        },
      ],
      lastModified: '2025-12-01',
    },
  },
  {
    id: 'student-8',
    name: 'Olivia Johnson',
    firstName: 'Olivia',
    lastName: 'Johnson',
    gradeLevel: '6',
    averageScore: 77,
    progressPercentage: 60,
    assignmentsCompleted: 13,
    totalAssignments: 20,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    engagementLevel: 'medium',
    hasIep: false,
    has504: false,
    riskLevel: 'low',
  },
];

// Mock Classes
export const mockClasses: Class[] = [
  {
    id: 'class-1',
    name: 'Algebra I - Period 1',
    subject: 'Mathematics',
    gradeLevel: '6',
    period: '1',
    room: '204',
    teacherId: 'teacher-1',
    schoolYear: '2025-2026',
    startDate: '2025-09-01',
    endDate: '2026-06-15',
    students: mockStudents.slice(0, 6).map((s, i) => ({
      id: `enrollment-${i + 1}`,
      classId: 'class-1',
      learnerId: s.id,
      enrolledAt: '2025-09-01',
      status: 'active' as const,
      learner: s,
    })),
    studentCount: 6,
    averageScore: 81,
    color: 'bg-blue-500',
  },
  {
    id: 'class-2',
    name: 'Algebra I - Period 3',
    subject: 'Mathematics',
    gradeLevel: '6',
    period: '3',
    room: '204',
    teacherId: 'teacher-1',
    schoolYear: '2025-2026',
    startDate: '2025-09-01',
    endDate: '2026-06-15',
    students: mockStudents.slice(2, 8).map((s, i) => ({
      id: `enrollment-${i + 7}`,
      classId: 'class-2',
      learnerId: s.id,
      enrolledAt: '2025-09-01',
      status: 'active' as const,
      learner: s,
    })),
    studentCount: 6,
    averageScore: 78,
    color: 'bg-green-500',
  },
  {
    id: 'class-3',
    name: 'Geometry - Period 5',
    subject: 'Mathematics',
    gradeLevel: '7',
    period: '5',
    room: '204',
    teacherId: 'teacher-1',
    schoolYear: '2025-2026',
    startDate: '2025-09-01',
    endDate: '2026-06-15',
    students: mockStudents.slice(4, 8).map((s, i) => ({
      id: `enrollment-${i + 13}`,
      classId: 'class-3',
      learnerId: s.id,
      enrolledAt: '2025-09-01',
      status: 'active' as const,
      learner: s,
    })),
    studentCount: 4,
    averageScore: 85,
    color: 'bg-purple-500',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalStudents: 28,
  studentsChange: 2,
  activeClasses: 5,
  averageMastery: 81,
  masteryChange: 3,
  atRiskStudents: 3,
  atRiskChange: -1,
  iepStudents: 3,
  plan504Students: 2,
  pendingGrades: 12,
  unreadMessages: 4,
  upcomingDeadlines: 3,
};

// Mock Intervention Alerts
export const mockInterventionAlerts: InterventionAlert[] = [
  {
    id: 'alert-1',
    studentId: 'student-4',
    studentName: 'Michael Davis',
    type: 'academic',
    severity: 'high',
    title: '3 missing assignments',
    description: 'Student has not submitted homework for the past week. Multiple reminders sent.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    actionRequired: 'Contact parent and schedule intervention meeting',
    suggestedActions: ['Contact Parent', 'Schedule Meeting', 'Assign Buddy'],
  },
  {
    id: 'alert-2',
    studentId: 'student-3',
    studentName: 'Jordan Lee',
    type: 'engagement',
    severity: 'medium',
    title: 'Low participation in class',
    description: 'Engagement has dropped significantly over the past 2 weeks.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    actionRequired: 'Check in with student and review 504 accommodations',
    suggestedActions: ['1-on-1 Check-in', 'Review 504', 'Modify Seating'],
  },
  {
    id: 'alert-3',
    studentId: 'student-2',
    studentName: 'Alex Smith',
    type: 'iep_goal',
    severity: 'medium',
    title: 'IEP goal at risk',
    description: 'Writing goal progress has stalled. May need intervention adjustment.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    relatedGoalId: 'goal-2',
    actionRequired: 'Review IEP goal and consider modifications',
    suggestedActions: ['IEP Team Meeting', 'Adjust Goal', 'Add Support'],
  },
];

// Mock Recent Activity
export const mockRecentActivity: RecentActivityItem[] = [
  {
    id: 'activity-1',
    type: 'assignment_submitted',
    title: 'Submitted assignment',
    description: 'Chapter 5 Homework',
    studentId: 'student-1',
    studentName: 'Emma Wilson',
    classId: 'class-1',
    className: 'Algebra I',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'activity-2',
    type: 'message_received',
    title: 'New message from',
    description: 'Question about upcoming test',
    studentName: 'Parent: Sarah Smith',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'activity-3',
    type: 'grade_updated',
    title: 'Grade updated for',
    description: 'Quiz 3: 85%',
    studentId: 'student-5',
    studentName: 'Sophia Martinez',
    classId: 'class-1',
    className: 'Algebra I',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'activity-4',
    type: 'iep_updated',
    title: 'IEP progress note added',
    description: 'Reading comprehension improving',
    studentId: 'student-2',
    studentName: 'Alex Smith',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'activity-5',
    type: 'assignment_submitted',
    title: 'Submitted assignment',
    description: 'Practice Problems Set 4',
    studentId: 'student-6',
    studentName: 'Liam Chen',
    classId: 'class-1',
    className: 'Algebra I',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

// Mock Upcoming Lessons
export const mockUpcomingLessons: UpcomingLesson[] = [
  {
    id: 'lesson-1',
    classId: 'class-1',
    className: 'Algebra I - Period 1',
    title: 'Solving Linear Equations',
    description: 'Introduction to one-step equations',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '09:00',
    duration: 45,
    status: 'scheduled',
    lessonType: 'lecture',
    standards: ['CCSS.MATH.6.EE.7'],
  },
  {
    id: 'lesson-2',
    classId: 'class-2',
    className: 'Algebra I - Period 3',
    title: 'Equation Practice',
    description: 'Hands-on practice with manipulatives',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '11:00',
    duration: 45,
    status: 'scheduled',
    lessonType: 'activity',
  },
  {
    id: 'lesson-3',
    classId: 'class-3',
    className: 'Geometry - Period 5',
    title: 'Introduction to Angles',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString().split('T')[0],
    scheduledTime: '14:00',
    duration: 45,
    status: 'scheduled',
    lessonType: 'lecture',
  },
];

// Mock Upcoming Events
export const mockUpcomingEvents: UpcomingEvent[] = [
  {
    id: 'event-1',
    type: 'parent_conference',
    title: 'Parent-Teacher Conference',
    description: 'Scheduled conference with Smith family',
    studentId: 'student-2',
    studentName: 'Alex Smith',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString().split('T')[0],
    scheduledTime: '16:00',
    duration: 30,
    location: 'Room 204',
  },
  {
    id: 'event-2',
    type: 'iep_review',
    title: 'IEP Annual Review',
    description: 'Annual review meeting for Taylor Brown',
    studentId: 'student-7',
    studentName: 'Taylor Brown',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString().split('T')[0],
    scheduledTime: '15:00',
    duration: 60,
    location: 'Conference Room B',
  },
];

// Mock Class Performance Data
export const mockClassPerformance: ClassPerformanceData[] = [
  {
    classId: 'class-1',
    className: 'Algebra I - Period 1',
    averageScore: 81,
    studentCount: 28,
    trend: 'up',
    trendValue: 3,
    masteryDistribution: {
      mastered: 25,
      proficient: 40,
      developing: 25,
      beginning: 10,
    },
    weeklyProgress: [
      { week: 'Week 1', averageScore: 75, engagement: 80, completionRate: 85 },
      { week: 'Week 2', averageScore: 77, engagement: 82, completionRate: 88 },
      { week: 'Week 3', averageScore: 78, engagement: 79, completionRate: 82 },
      { week: 'Week 4', averageScore: 80, engagement: 85, completionRate: 90 },
      { week: 'Week 5', averageScore: 81, engagement: 87, completionRate: 92 },
    ],
  },
  {
    classId: 'class-2',
    className: 'Algebra I - Period 3',
    averageScore: 78,
    studentCount: 26,
    trend: 'stable',
    trendValue: 0,
    masteryDistribution: {
      mastered: 20,
      proficient: 35,
      developing: 30,
      beginning: 15,
    },
    weeklyProgress: [
      { week: 'Week 1', averageScore: 76, engagement: 75, completionRate: 80 },
      { week: 'Week 2', averageScore: 77, engagement: 78, completionRate: 82 },
      { week: 'Week 3', averageScore: 78, engagement: 76, completionRate: 79 },
      { week: 'Week 4', averageScore: 77, engagement: 80, completionRate: 85 },
      { week: 'Week 5', averageScore: 78, engagement: 82, completionRate: 87 },
    ],
  },
  {
    classId: 'class-3',
    className: 'Geometry - Period 5',
    averageScore: 85,
    studentCount: 22,
    trend: 'up',
    trendValue: 5,
    masteryDistribution: {
      mastered: 35,
      proficient: 40,
      developing: 20,
      beginning: 5,
    },
    weeklyProgress: [
      { week: 'Week 1', averageScore: 80, engagement: 85, completionRate: 90 },
      { week: 'Week 2', averageScore: 82, engagement: 88, completionRate: 92 },
      { week: 'Week 3', averageScore: 83, engagement: 86, completionRate: 88 },
      { week: 'Week 4', averageScore: 84, engagement: 90, completionRate: 95 },
      { week: 'Week 5', averageScore: 85, engagement: 92, completionRate: 96 },
    ],
  },
];

// Combined Dashboard Data
export const mockDashboardData: DashboardData = {
  stats: mockDashboardStats,
  activities: mockRecentActivity,
  lessons: mockUpcomingLessons,
  alerts: mockInterventionAlerts,
  performance: mockClassPerformance,
  upcomingEvents: mockUpcomingEvents,
};

// Helper function to get dashboard data for a specific class
export function getClassDashboardData(classId: string): DashboardData | null {
  const classData = mockClasses.find((c) => c.id === classId);
  if (!classData) return null;

  const studentIds = classData.students.map((s) => s.learnerId);

  return {
    stats: {
      totalStudents: classData.studentCount,
      activeClasses: 1,
      averageMastery: classData.averageScore || 0,
      atRiskStudents: classData.students.filter(
        (s) => s.learner.riskLevel && ['medium', 'high', 'critical'].includes(s.learner.riskLevel)
      ).length,
      iepStudents: classData.students.filter((s) => s.learner.hasIep).length,
      plan504Students: classData.students.filter((s) => s.learner.has504).length,
      pendingGrades: Math.floor(Math.random() * 10),
      unreadMessages: Math.floor(Math.random() * 5),
      upcomingDeadlines: 2,
    },
    activities: mockRecentActivity.filter(
      (a) => a.classId === classId || (a.studentId && studentIds.includes(a.studentId))
    ),
    lessons: mockUpcomingLessons.filter((l) => l.classId === classId),
    alerts: mockInterventionAlerts.filter((a) => studentIds.includes(a.studentId)),
    performance: mockClassPerformance.filter((p) => p.classId === classId),
    upcomingEvents: mockUpcomingEvents.filter(
      (e) => e.classId === classId || (e.studentId && studentIds.includes(e.studentId))
    ),
  };
}
