-- ══════════════════════════════════════════════════════════════════════════════
-- Explanation & Justification Events Schema
-- Migration: 20241210000000_explanation_events
--
-- Purpose:
--   Creates a structured, auditable trail of explanations for key platform
--   decisions: content selection, difficulty adjustments, focus breaks,
--   and recommendations.
--
-- Design Principles:
--   - Human-readable summaries + machine-parsable details
--   - Multi-tenant isolation via tenant_id
--   - Privacy-aware: neutral, strength-based language only
--   - Links to existing entities (ai_call_logs, sessions, etc.)
--
-- Retention Policy:
--   - Derived explanatory data (not raw PII)
--   - Retained per tenant data governance policy
--   - Subject to DSR deletion requests (via learner_id)
-- ══════════════════════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────────────────────────────────────
-- ENUMS
-- ────────────────────────────────────────────────────────────────────────────

-- Source systems that generate explanations
CREATE TYPE explanation_source_type AS ENUM (
  'LESSON_PLANNER',      -- LessonPlannerAgent content sequencing
  'VIRTUAL_BRAIN',       -- VirtualBrainAgent adaptive tutoring
  'FOCUS_AGENT',         -- FocusAgent break/intervention decisions
  'RECOMMENDER',         -- Recommendation service suggestions
  'SYSTEM_POLICY',       -- Automated policy enforcement
  'BASELINE_AGENT',      -- BaselineAgent assessment decisions
  'HOMEWORK_HELPER'      -- HomeworkHelperAgent scaffolding decisions
);

-- Types of actions being explained
CREATE TYPE explanation_action_type AS ENUM (
  'CONTENT_SELECTION',         -- Why specific content was chosen
  'DIFFICULTY_CHANGE',         -- Why difficulty was adjusted up/down
  'FOCUS_BREAK_TRIGGER',       -- Why a focus break was suggested
  'FOCUS_INTERVENTION',        -- Why a focus intervention was shown
  'MODULE_RECOMMENDATION',     -- Why a module was recommended to parent/teacher
  'LEARNING_PATH_ADJUSTMENT',  -- Why the learning path was modified
  'SKILL_PROGRESSION',         -- Why learner moved to next skill
  'SCAFFOLDING_DECISION',      -- Why specific scaffolding was applied
  'POLICY_ENFORCEMENT'         -- Why a policy rule was applied
);

-- ────────────────────────────────────────────────────────────────────────────
-- TABLE: explanation_events
--
-- Core table storing every explanation generated by the platform.
-- Each row represents one explainable decision with both human-readable
-- summary and machine-parsable details.
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS explanation_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Context / Scope
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Multi-tenant isolation (REQUIRED)
  tenant_id UUID NOT NULL,
  
  -- Learner context (nullable for tenant-wide explanations)
  learner_id UUID,
  
  -- Recipient context: who should see this explanation
  -- e.g., parent viewing dashboard, teacher reviewing progress
  user_id UUID,
  
  -- Session context (nullable for non-session decisions)
  session_id UUID,
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Classification
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Which system generated this explanation
  source_type explanation_source_type NOT NULL,
  
  -- What kind of decision is being explained
  action_type explanation_action_type NOT NULL,
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Related Entity
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Type of the entity this explanation relates to
  -- Examples: 'LEARNING_OBJECT_VERSION', 'RECOMMENDATION', 'SKILL', 
  --           'SESSION_EVENT', 'EXPERIMENT', 'POLICY_RULE'
  related_entity_type TEXT NOT NULL,
  
  -- ID of the related entity (could be UUID or other identifier)
  related_entity_id TEXT NOT NULL,
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Explanation Content
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Human-readable explanation (1-2 sentences)
  -- MUST use neutral, strength-based language.
  -- NO sensitive diagnoses or defamatory language.
  -- Examples:
  --   "We chose easier fractions tasks based on recent performance."
  --   "A short break was suggested after 25 minutes of focused practice."
  --   "This module is recommended to help strengthen multiplication skills."
  summary_text TEXT NOT NULL,
  
  -- Machine-readable details (for agents/analytics)
  -- Standard structure:
  -- {
  --   "reasons": [
  --     { "code": "LOW_MASTERY", "weight": 0.7, "description": "Mastery score below threshold" },
  --     { "code": "RECENT_STRUGGLE", "weight": 0.3, "description": "3 incorrect attempts in last session" }
  --   ],
  --   "inputs": {
  --     "masteryScore": 0.42,
  --     "recentAccuracy": 0.33,
  --     "focusScore": 0.85,
  --     "sessionDurationMinutes": 25
  --   },
  --   "thresholds": {
  --     "masteryThreshold": 0.6,
  --     "accuracyThreshold": 0.5
  --   },
  --   "policyReferences": ["DIFFICULTY_ADAPTATION_V1"],
  --   "experimentKey": "difficulty_adjustment_experiment",
  --   "variantId": "aggressive_reduction"
  -- }
  details_json JSONB NOT NULL DEFAULT '{}',
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- AI Traceability
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Link to AI call that generated this explanation (if AI-generated)
  ai_call_log_id UUID,
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Template Reference (optional)
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Reference to the template used to generate summary_text
  template_id UUID,
  
  -- ═══════════════════════════════════════════════════════════════════════════
  -- Metadata
  -- ═══════════════════════════════════════════════════════════════════════════
  
  -- Confidence score (0-1) if the explanation involves ML/probabilistic reasoning
  confidence NUMERIC(4,3),
  
  -- Version of the explanation generation logic
  generator_version TEXT NOT NULL DEFAULT '1.0.0',
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- TABLE: explanation_templates
--
-- Pre-defined templates for generating consistent, reviewed explanations.
-- Templates ensure language is vetted for appropriateness and clarity.
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS explanation_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Which source/action this template applies to
  source_type explanation_source_type NOT NULL,
  action_type explanation_action_type NOT NULL,
  
  -- Unique key for programmatic lookup
  -- Examples: 'DIFFICULTY_DOWN_STRUGGLE_GENERIC', 'FOCUS_BREAK_TIME_BASED'
  template_key TEXT NOT NULL UNIQUE,
  
  -- Human-readable name for admin UI
  display_name TEXT NOT NULL,
  
  -- Template text with placeholders
  -- Placeholders use {variable} syntax
  -- Examples:
  --   "We adjusted {subject} to a slightly easier level because {reason}."
  --   "A break was suggested after {duration} of focused practice to help maintain attention."
  --   "We recommended {module_name} based on {learner_name}'s progress in {skill_area}."
  template_text TEXT NOT NULL,
  
  -- JSON Schema for validating placeholder values
  -- Ensures all required placeholders are provided
  placeholders_schema JSONB NOT NULL DEFAULT '{}',
  
  -- Whether this template is active and can be used
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  
  -- Audit trail
  created_by UUID,
  updated_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────────────────
-- INDEXES
--
-- Optimized for common query patterns:
-- 1. Tenant dashboard: filter by tenant, optionally by learner, time-ordered
-- 2. Action audit: filter by action type within tenant
-- 3. Entity lookup: find explanations for a specific entity
-- 4. AI traceability: join with ai_call_logs
-- ────────────────────────────────────────────────────────────────────────────

-- Primary tenant + learner queries (most common dashboard pattern)
CREATE INDEX idx_explanation_events_tenant_learner_created
  ON explanation_events (tenant_id, learner_id, created_at DESC)
  WHERE learner_id IS NOT NULL;

-- Tenant-wide explanations (no learner)
CREATE INDEX idx_explanation_events_tenant_created
  ON explanation_events (tenant_id, created_at DESC);

-- Action type filtering (audit queries)
CREATE INDEX idx_explanation_events_tenant_action_created
  ON explanation_events (tenant_id, action_type, created_at DESC);

-- Source type filtering (debugging agent behavior)
CREATE INDEX idx_explanation_events_tenant_source_created
  ON explanation_events (tenant_id, source_type, created_at DESC);

-- Related entity lookup (find explanations for specific content/recommendation)
CREATE INDEX idx_explanation_events_entity
  ON explanation_events (related_entity_type, related_entity_id);

-- Session replay (show all explanations within a session)
CREATE INDEX idx_explanation_events_session
  ON explanation_events (session_id, created_at)
  WHERE session_id IS NOT NULL;

-- AI traceability (join with ai_call_logs)
CREATE INDEX idx_explanation_events_ai_call
  ON explanation_events (ai_call_log_id)
  WHERE ai_call_log_id IS NOT NULL;

-- User-specific explanations (parent/teacher dashboard)
CREATE INDEX idx_explanation_events_user
  ON explanation_events (user_id, created_at DESC)
  WHERE user_id IS NOT NULL;

-- Template lookup by key
CREATE INDEX idx_explanation_templates_key
  ON explanation_templates (template_key)
  WHERE is_active = TRUE;

-- Template lookup by source + action
CREATE INDEX idx_explanation_templates_source_action
  ON explanation_templates (source_type, action_type)
  WHERE is_active = TRUE;

-- ────────────────────────────────────────────────────────────────────────────
-- GIN INDEX for JSONB queries
-- ────────────────────────────────────────────────────────────────────────────

-- Enable queries into details_json structure
-- Examples:
--   SELECT * FROM explanation_events 
--   WHERE details_json @> '{"reasons": [{"code": "LOW_MASTERY"}]}';
CREATE INDEX idx_explanation_events_details_gin
  ON explanation_events USING GIN (details_json jsonb_path_ops);

-- ────────────────────────────────────────────────────────────────────────────
-- COMMENTS
-- ────────────────────────────────────────────────────────────────────────────

COMMENT ON TABLE explanation_events IS 
'Stores structured explanations for platform decisions (content selection, difficulty changes, etc.).
Each explanation includes both human-readable summary and machine-parsable details.

PRIVACY REQUIREMENTS:
- summary_text MUST use neutral, strength-based language
- NO sensitive diagnoses or defamatory language
- Subject to DSR deletion via learner_id

RETENTION: Per tenant data governance policy. Typically 1-3 years.';

COMMENT ON COLUMN explanation_events.summary_text IS 
'Human-readable explanation (1-2 sentences). MUST be appropriate for display to parents/teachers.
Use neutral, encouraging language. Example: "We chose easier tasks to help build confidence."';

COMMENT ON COLUMN explanation_events.details_json IS 
'Machine-readable explanation details. Standard structure:
- reasons: array of {code, weight, description}
- inputs: key-value pairs of input signals/metrics
- thresholds: comparison values used in decision
- policyReferences: applicable policy identifiers
- experimentKey: A/B test identifier if applicable';

COMMENT ON COLUMN explanation_events.related_entity_type IS 
'Type of entity this explanation relates to. Common values:
LEARNING_OBJECT_VERSION, RECOMMENDATION, SKILL, SESSION_EVENT, EXPERIMENT, POLICY_RULE';

COMMENT ON TABLE explanation_templates IS 
'Pre-defined, vetted templates for generating consistent explanations.
Templates ensure language quality and appropriateness across the platform.';

COMMENT ON COLUMN explanation_templates.template_text IS 
'Template with {placeholder} variables. Placeholders are validated against placeholders_schema.
Example: "We adjusted {subject} difficulty because {reason}."';

-- ────────────────────────────────────────────────────────────────────────────
-- SEED DATA: Default Explanation Templates
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO explanation_templates (source_type, action_type, template_key, display_name, template_text, placeholders_schema)
VALUES
  -- Difficulty Changes
  ('VIRTUAL_BRAIN', 'DIFFICULTY_CHANGE', 'DIFFICULTY_DOWN_STRUGGLE', 
   'Difficulty Reduced (Struggling)',
   'We adjusted {subject} to an easier level to help build confidence. {learner_name} can work at a comfortable pace while strengthening foundational skills.',
   '{"type": "object", "required": ["subject", "learner_name"], "properties": {"subject": {"type": "string"}, "learner_name": {"type": "string"}}}'),
  
  ('VIRTUAL_BRAIN', 'DIFFICULTY_CHANGE', 'DIFFICULTY_UP_MASTERY',
   'Difficulty Increased (Mastery)',
   'Great progress! {learner_name} is ready for more challenging {subject} tasks after demonstrating strong understanding.',
   '{"type": "object", "required": ["subject", "learner_name"], "properties": {"subject": {"type": "string"}, "learner_name": {"type": "string"}}}'),
  
  -- Focus Breaks
  ('FOCUS_AGENT', 'FOCUS_BREAK_TRIGGER', 'FOCUS_BREAK_TIME_BASED',
   'Focus Break (Time)',
   'A short break was suggested after {duration_minutes} minutes of focused practice to help maintain attention and energy.',
   '{"type": "object", "required": ["duration_minutes"], "properties": {"duration_minutes": {"type": "number"}}}'),
  
  ('FOCUS_AGENT', 'FOCUS_BREAK_TRIGGER', 'FOCUS_BREAK_ATTENTION',
   'Focus Break (Attention)',
   'We noticed some signs of distraction and suggested a quick break. Brief pauses help learners return refreshed and ready to learn.',
   '{"type": "object", "properties": {}}'),
  
  ('FOCUS_AGENT', 'FOCUS_INTERVENTION', 'FOCUS_INTERVENTION_ACTIVITY',
   'Focus Intervention Activity',
   'A quick movement activity was suggested to help {learner_name} reset and refocus for continued learning.',
   '{"type": "object", "required": ["learner_name"], "properties": {"learner_name": {"type": "string"}}}'),
  
  -- Content Selection
  ('LESSON_PLANNER', 'CONTENT_SELECTION', 'CONTENT_SKILL_GAP',
   'Content Selected (Skill Gap)',
   'We selected {content_name} to address {skill_area}, an area identified for growth based on recent practice.',
   '{"type": "object", "required": ["content_name", "skill_area"], "properties": {"content_name": {"type": "string"}, "skill_area": {"type": "string"}}}'),
  
  ('LESSON_PLANNER', 'CONTENT_SELECTION', 'CONTENT_REINFORCEMENT',
   'Content Selected (Reinforcement)',
   'Additional practice with {content_name} was included to strengthen {learner_name}''s growing understanding of {skill_area}.',
   '{"type": "object", "required": ["content_name", "learner_name", "skill_area"], "properties": {"content_name": {"type": "string"}, "learner_name": {"type": "string"}, "skill_area": {"type": "string"}}}'),
  
  -- Recommendations
  ('RECOMMENDER', 'MODULE_RECOMMENDATION', 'RECOMMEND_NEXT_SKILL',
   'Module Recommended (Next Skill)',
   'We recommend {module_name} as the next step in {learner_name}''s learning journey, building on their recent progress in {prerequisite_skill}.',
   '{"type": "object", "required": ["module_name", "learner_name", "prerequisite_skill"], "properties": {"module_name": {"type": "string"}, "learner_name": {"type": "string"}, "prerequisite_skill": {"type": "string"}}}'),
  
  ('RECOMMENDER', 'MODULE_RECOMMENDATION', 'RECOMMEND_PRACTICE',
   'Module Recommended (Practice)',
   'Additional practice with {module_name} is suggested to help solidify {learner_name}''s understanding before moving forward.',
   '{"type": "object", "required": ["module_name", "learner_name"], "properties": {"module_name": {"type": "string"}, "learner_name": {"type": "string"}}}'),
  
  -- Learning Path
  ('LESSON_PLANNER', 'LEARNING_PATH_ADJUSTMENT', 'PATH_ACCELERATE',
   'Learning Path Accelerated',
   '{learner_name} is progressing well and ready to move ahead in {subject}. The learning path has been adjusted to introduce new concepts sooner.',
   '{"type": "object", "required": ["learner_name", "subject"], "properties": {"learner_name": {"type": "string"}, "subject": {"type": "string"}}}'),
  
  ('LESSON_PLANNER', 'LEARNING_PATH_ADJUSTMENT', 'PATH_REINFORCE',
   'Learning Path Adjusted (More Practice)',
   'The learning path for {learner_name} now includes additional practice opportunities in {skill_area} to ensure a strong foundation.',
   '{"type": "object", "required": ["learner_name", "skill_area"], "properties": {"learner_name": {"type": "string"}, "skill_area": {"type": "string"}}}'),
  
  -- Scaffolding
  ('HOMEWORK_HELPER', 'SCAFFOLDING_DECISION', 'SCAFFOLD_HINT',
   'Hint Provided',
   'A hint was provided to guide {learner_name} toward the solution while encouraging independent problem-solving.',
   '{"type": "object", "required": ["learner_name"], "properties": {"learner_name": {"type": "string"}}}'),
  
  ('HOMEWORK_HELPER', 'SCAFFOLDING_DECISION', 'SCAFFOLD_STEP_BREAKDOWN',
   'Problem Broken Down',
   'This problem was broken into smaller steps to help {learner_name} work through it more confidently.',
   '{"type": "object", "required": ["learner_name"], "properties": {"learner_name": {"type": "string"}}}'),
  
  -- Policy Enforcement
  ('SYSTEM_POLICY', 'POLICY_ENFORCEMENT', 'POLICY_TIME_LIMIT',
   'Session Time Limit',
   'The session was paused after reaching the {duration_minutes}-minute recommended limit. Regular breaks support healthy learning habits.',
   '{"type": "object", "required": ["duration_minutes"], "properties": {"duration_minutes": {"type": "number"}}}'),
  
  ('SYSTEM_POLICY', 'POLICY_ENFORCEMENT', 'POLICY_CONTENT_FILTER',
   'Content Filtered',
   'Some content was adjusted to align with the learning goals and policies set for this account.',
   '{"type": "object", "properties": {}}')

ON CONFLICT (template_key) DO NOTHING;
